title: Corporate
headline: Jual Segala Macam Perkakas Rumah Tangga
url: https://dev.orderio.id
description: Mau cari perlengkapan rumah? Pesan via chat WA di sini!
keywords: dekorasi, perkakas, rumah, tangga
copyright: "2021"
ogp: /assets/upload/config/ogp.jpeg
whatsapp_number: 6281234567890
whatsapp_chat: |-
  Halo kak...
  Saya mau order :
